# Generated by Django 2.2.20 on 2021-09-09 16:11

from django.db import migrations
import phonenumbers


def normalize_phone(apps, schema_editor):
    Flat = apps.get_model("property", "Flat")
    for flat in Flat.objects.filter(owners_phonenumber__isnull=False):
        if phonenumbers.is_valid_number(
                phone := phonenumbers.parse(flat.owners_phonenumber, "RU")
        ):
            flat.owner_pure_phone = phonenumbers.format_number(
                    phone, phonenumbers.PhoneNumberFormat.E164
                )
            flat.save()


def rollback(apps, schema_editor):
    Flat = apps.get_model("property", "Flat")
    Flat.objects.filter(owners_phonenumber__isnull=False).update(
        owner_pure_phone=None
    )


class Migration(migrations.Migration):

    dependencies = [
        ("property", "0007_auto_20210909_1714"),
    ]

    operations = [migrations.RunPython(normalize_phone, rollback)]
