# Generated by Django 2.2.20 on 2021-09-10 11:21

from django.db import migrations

def update_owners(apps, schema_editor ):
    Flat = apps.get_model("property", "Flat")
    Owner = apps.get_model("property", "Owner")

    for flat in Flat.objects.all():
        owner, created = Owner.objects.get_or_create(
            name = flat.owner,
            owners_phonenumber = flat.owners_phonenumber,
            owner_pure_phone=flat.owner_pure_phone
        )
        if flat not in owner.flat.all():
            owner.flat.add(flat)
            owner.save()

def rollback(apps, schema_editor):
    Owner = apps.get_model("property", "Owner")
    Owner.objects.all().delete()



class Migration(migrations.Migration):

    dependencies = [
        ('property', '0009_auto_20210910_1419'),
    ]

    operations = [
        migrations.RunPython(update_owners, rollback)
    ]
