# Generated by Django 2.2.20 on 2021-09-10 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0010_update_owners'),
    ]

    operations = [
        migrations.AlterField(
            model_name='owner',
            name='flat',
            field=models.ManyToManyField(blank=True, default=[], related_name='owners', to='property.Flat'),
        ),
    ]
