# Generated by Django 2.2.20 on 2021-09-10 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0011_auto_20210910_1706'),
    ]

    operations = [
        migrations.AlterField(
            model_name='owner',
            name='flat',
            field=models.ManyToManyField(blank=True, default=[], related_name='owned_by', to='property.Flat'),
        ),
    ]
